import { Localization } from "@sse-auth/types/localization";

export const hiIN: Localization = {
  id: "Hindi",
  signIn: {
    title: "अपने खाते में साइन इन करें",
    subtitle: "आपका फिर से स्वागत है! जारी रखने के लिए अपनी जानकारी दर्ज करें।",
    label_email: "ईमेल पता",
    label_password: "पासवर्ड",
    label_phone: "फोन नंबर",
    link_forgotPassword: "क्या आप अपना पासवर्ड भूल गए?",
    submit_text: "साइन इन करें",
    divider_text: "या जारी रखें",
    social_text: "साइन इन करें {{provider}} के साथ",
    link_dontHaveAnAccount: "क्या आपके पास खाता नहीं है?",
    createAccount: "खाता बनाएं",
  },
  signUp: {
    title: "अपना खाता बनाएं",
    subtitle: "खाता बनाने और शुरू करने के लिए अपनी जानकारी दर्ज करें।",
    label_email: "ईमेल पता",
    label_password: "पासवर्ड",
    label_phone: "फोन नंबर",
    label_name: "नाम",
    submit_text: "खाता बनाएं",
    divider_text: "या जारी रखें",
    link_haveAnAccount: "क्या आपके पास पहले से खाता है?",
    login: "लॉगिन",
    label_firstName: "पहला नाम",
    label_lastName: "अंतिम नाम",
  },
  user: {
    dropdown: {
      manage: "प्रबंधित करें",
      signOut: "साइन आउट करें",
      switchAccount: "खाता बदलें",
      preferences: "पसंद",
      help: "मदद",
      sendFeedback: "फीडबैक भेजें",
    },
    edit: {
      sidebar: { account: "खाता", security: "सुरक्षा", help: "मदद" },
      accounts: {
        title: "खाता",
        subtitle: "अपने खाता जानकारी का प्रबंधन करें",
        profile: "प्रोफ़ाइल",
        emailAddresses: {
          title: "ईमेल पते",
          primaryEmailAddress: "प्राथमिक ईमेल पता",
          primaryEmailAddress_subtitle: "ईमेल पता प्राथमिक ईमेल पता है",
          remove: "हटाएं",
          remove_subtitle: "इस ईमेल पते को हटाएं और इसे अपने खाते से हटा दें",
          removeemailAddress: "ईमेल पता हटाएं",
          addAsEmailAddress: "ईमेल पता जोड़ें",
        },
        connectedAccounts: {
          title: "जुड़े हुए खाते",
          connectAccount: "खाता कनेक्ट करें",
          remove: "हटाएं",
          remove_subtitle: "इस जुड़े हुए खाते को अपने खाते से हटा दें",
          removeConnectAccount: "जुड़ा हुआ खाता हटाएं",
        },
      },
      security: {
        title: "सुरक्षा",
        password: "पासवर्ड",
        setPassword: "पासवर्ड सेट करें",
        activeDevices: "सक्रिय उपकरण",
        changePassword: "पासवर्ड बदलें",
      },
      setPassword: {
        title: "पासवर्ड सेट करें",
        newPassword: "नया पासवर्ड",
        confirmPassword: "पासवर्ड की पुष्टि करें",
        lenError: "आपका पासवर्ड 8 या अधिक वर्णों में होना चाहिए।",
        confirmPasswordError: "पासवर्ड मेल नहीं खाता",
        signOutAllDevices: "सभी अन्य उपकरणों से साइन आउट करें",
        cancel: "रद्द करें",
        continue: "जारी रखें",
      },
      addConnectedAccount: {
        title: "जुड़े हुए उपकरण जोड़ें",
        noProviderError: "कोई उपलब्ध बाहरी खाता प्रदाता नहीं है।",
        cancel: "रद्द करें",
      },
      updateProfile: {
        title: "प्रोफ़ाइल अपडेट करें",
        profileImage: "प्रोफ़ाइल छवि",
        uploadImage: "छवि अपलोड करें",
        removeImage: "छवि हटाएं",
        cancel: "रद्द करें",
        continue: "जारी रखें",
      },
    },
  },
};
