import { Localization } from "@sse-auth/types/localization";

export const zhCN: Localization = {
  id: "简体中文",
  signIn: {
    title: "登录您的账户",
    subtitle: "欢迎回来！请输入您的信息以继续。",
    label_email: "电子邮件地址",
    label_password: "密码",
    label_phone: "电话号码",
    link_forgotPassword: "忘记密码？",
    submit_text: "登录",
    divider_text: "或继续使用",
    social_text: "使用 {{provider}} 登录",
    link_dontHaveAnAccount: "还没有账户？",
    createAccount: "创建账户",
  },
  signUp: {
    title: "创建您的账户",
    subtitle: "输入您的信息以创建账户并开始使用。",
    label_email: "电子邮件地址",
    label_password: "密码",
    label_phone: "电话号码",
    label_name: "姓名",
    submit_text: "创建账户",
    divider_text: "或继续使用",
    link_haveAnAccount: "已经有账户？",
    login: "登录",
    label_firstName: "名字",
    label_lastName: "姓氏",
  },
  user: {
    dropdown: {
      manage: "管理",
      signOut: "登出",
      switchAccount: "切换账户",
      preferences: "偏好设置",
      help: "帮助",
      sendFeedback: "发送反馈",
    },
    edit: {
      sidebar: { account: "账户", security: "安全", help: "帮助" },
      accounts: {
        title: "账户",
        subtitle: "管理您的账户信息",
        profile: "个人资料",
        emailAddresses: {
          title: "电子邮件地址",
          primaryEmailAddress: "主要电子邮件地址",
          primaryEmailAddress_subtitle: "该电子邮件地址是主要电子邮件地址",
          remove: "移除",
          remove_subtitle: "删除此电子邮件地址并将其从您的账户中移除",
          removeemailAddress: "移除电子邮件地址",
          addAsEmailAddress: "添加电子邮件地址",
        },
        connectedAccounts: {
          title: "连接的账户",
          connectAccount: "连接账户",
          remove: "移除",
          remove_subtitle: "从您的账户中移除此连接的账户",
          removeConnectAccount: "移除连接的账户",
        },
      },
      security: {
        title: "安全",
        password: "密码",
        setPassword: "设置密码",
        activeDevices: "活跃设备",
        changePassword: "更改密码",
      },
      setPassword: {
        title: "设置密码",
        newPassword: "新密码",
        confirmPassword: "确认密码",
        lenError: "您的密码必须包含8个或更多字符。",
        confirmPasswordError: "密码不匹配",
        signOutAllDevices: "从所有其他设备登出",
        cancel: "取消",
        continue: "继续",
      },
      addConnectedAccount: {
        title: "添加连接的设备",
        noProviderError: "没有可用的外部账户提供者。",
        cancel: "取消",
      },
      updateProfile: {
        title: "更新个人资料",
        profileImage: "个人资料图片",
        uploadImage: "上传图片",
        removeImage: "移除图片",
        cancel: "取消",
        continue: "继续",
      },
    },
  },
};
