name: "Auto Assign"
on:
  schedule:
    - cron: 0 8 * * *
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.2
