# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Package name (npm)
        options:
          - "authenticator"
          - "backend"
          - "ip"
          - "locale"
          - "react"
          - "themes/plugins"
          - "themes/themer"
          - "types"
          - "providers"
          - "utils"

permissions:
  contents: write
  packages: write
  id-token: write

env:
  FORCE_COLOR: true
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    name: Publish NPM - ${{ github.event.inputs.name }}
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.name != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Run CI/CD
        run: npm ci

      # - name: Go to the file
      #   run: cd packages/${{ github.event.inputs.name }}

      # - name: Install Dependencies
      #   run: npm install

      # - name: Publish the Package
      #   run: npm publish --provenance --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the Package
        run: |
          cd packages/${{ github.event.inputs.name }}
          npm install
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
