name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate Changelog
        id: changelog
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-summary: true

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
